<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>higo_reviews_items</name>
   <tag></tag>
   <elementGuidId>c14cdccb-1744-424e-9386-9640a3570784</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
